6ITAll/book-it-da

.github/workflows/eslint-on-pr.yml

- #7
- pr 올리면 자동으로 eslint 검사되도록 처리하였습니다.
[노션 - Eslint Github Action 설정](https://www.notion.so/Eslint-Github-Action-eb9b89fa4ef648c9a5b7c636bd7e2706?pvs=24)
노션에 상세하게 작성해두었습니다.
- 예상 소요 : 2분
- 추가적인 Node.js 버전을 테스트하고 싶다면 15번 라인에 코멘트 남겨주세요!

:construction_worker:chore: add eslint on pr ci workflow

---

.gitmessage.txt

> #31
> 커밋 템플릿에 타입 추가하였습니다.
```
design: UI 디자인 변경
rename: 파일 위치 및 이름 변경
```
- 1분
- pull 해서 바로 사용하시면 됩니다!

커밋 템플릿 타입 추가

---

package-lock.json
package.json

- add mui icon package chore: #35 
- MUI 아이콘 추가

MUI 아이콘 추가

---

package-lock.json
package.json

- #48 
- Vite 내부 esbuild 버전 변경사항이 Vite 로더에 영향을 미침
- esbuild 다운그레이드하여 오버라이드
- esbuild 다운그레이드
- esbuild 0.24.1 > 0.24.0 버전으로 다운그레이드
- 5초
[Vite 공식 Github Issue](<https://github.com/vitejs/vite/issues/19018>)

Excepted identifier but found "import" 오류

---

package-lock.json
package.json

- #58 #59
- react-quill ➖
- react-quill-new ➕
- 패키지 설치 후 정상 작동 및 오류 메시지 표시되지 않는 점 확인했습니다.
- 리뷰 예상 시간: 10초

React Quill 대체

---

src/components/FeedPage/OneLineReviewDialog.tsx
src/components/commons/StarRating.tsx
src/shared/types/type.ts

별점 컴포넌트 추가
- #56
- 한줄평 다이얼로그에 별점 기능 추가
- 별점 공통 컴포넌트 추가
- 상세페이지 || 포스팅 타입 선택 다이얼로그에서 열 때 Props 분리 > UI 구성 변경
- 상세페이지에서 열 때
- 상세페이지에서의 책 표시
- 상세페이지에서 누른 별점 적용
- 포스팅 타입 선택 다이얼로그에서 열 때
- 책 검색 표시
- 뒤로가기 버튼 표시
- 별점 컴포넌트 추가
- 상세페이지에서 클릭할 경우 한줄평 다이얼로그 열기 
- 예시 코드
```
const [isDialogOpen, setIsDialogOpen] = useState(false);
const [rating, setRating] = useState<number>(0);
const mockBook = {
bookTitle: '해리포터와 마법사의 돌',
author: 'J.K. 롤링',
imageUrl: 'https://image.yes24.com/goods/1234567/L',
itemId: 1234567,
};
return (
<div>
<StarRating
rating={rating}
onRatingChange={setRating}
isDialog={false}
openDialog={() => setIsDialogOpen(true)}
/>
<OneLineReviewDialog
bookFromDetail={mockBook}
ratingFromDetail={rating}
isOpen={isDialogOpen}
onClose={() => setIsDialogOpen(false)}
/>
</div>
);
```
- 리뷰 예상 시간: …

한줄평 다이얼로그 별점 기능 추가

---

chromatic.config.json

- #76
- 스토리북 시각적 테스트 가능하도록 설정하였습니다.
- 시각적 테스트를 위해 필요한 chromatic 스토리북 배포하였습니다.
- 배포 링크: https://676e04e36c29268aa85682ba-ajvmwqjjie.chromatic.com/
- ⚠️ 지금 빌드되어 있는 HybridDialog는 아직 스토리 정식적으로 작성한게 아니라서 조금 이상한 부분이 있어도 양해 부탁드립니다! 배포 링크만 정상적으로 사이트 뜨는 지 확인해주시면 될 것 같아요!
- 시각적 테스트를 위해 필요한 chromatic 설정 파일 구성해주었습니다.
스토리북 실행(`npm run storybook`) 후 좌측 사이드바 하단의 visual Test 카드의 login require 클릭해서 크로마틱 로그인이 필요합니다.
저희 6ITAll 조직에 앱 접근 권한 허용해둬서 아마 계정 선택할 때 해당 6ITAll 선택이 가능할 것 같습니다. 6ITAll 조직 선택 후 book-it-da 레포 선택하면 될거에요!
저는 이미 프로젝트 세팅되어 있는 상태라서 다른 분들 프로젝트 연결할 때 어떻게 되는 지 파악이 어려워서 로그인 및 연동해보시고 이상한 점 있으면 알려주세용!

스토리북 시각적 테스트 추가

---

.github/workflows/storybook-tests.yml
package-lock.json
package.json

- #64
- PR 생성 시 자동으로 Storybook 관련 테스트를 실행하도록 CI 워크플로우를 추가했습니다.  
- UI 변경, 상호작용 테스트, 접근성 테스트, 시각적 테스트, 테스트 커버리지 확인을 한 번에 처리합니다.
1. **Install & Cache (install-cache)**
- 프로젝트 코드를 체크아웃하고, npm 의존성 및 playwright 브라우저를 캐싱
- 캐시에 없는 경우, 새로 의존성을 설치
- 브라우저 환경에서 테스트 진행하기 위해 playwright 브라우저 실행
2. **Storybook 상호작용 & 접근성 테스트 (interaction-and-accessibility)**
- 스토리북 빌드
- 로컬 서버 띄우고, 상호작용 및 접근성 테스트 수행
3. **시각적 & 컴포지션 테스트 (visual-and-composition)**
- Chromatic 액션을 통해 빌드된 스토리북 업로드
- UI 변경 사항을 시각적으로 비교하고, 컴포넌트 구성이 올바른지 확인
4. **사용자 플로우 테스트 (user-flow)**
- 개발 서버를 백그라운드에서 실행
- 브라우저 환경에서 실제 사용자 시나리오를 검증 (E2E 테스트라고 생각해주면 될 것 같습니다!)
5. **커버리지 보고서 생성 & 업로드 (storybook-coverage)**
- 스토리북을 빌드한 뒤, 커버리지 측정
- `coverage` 폴더 아티팩트로 업로드
- 실행 후 GitHub Actions의 “Actions” 탭에서 커버리지 확인 가능
- 예상 리뷰 시간: 15분
- 추가하고 싶은 workflow 있으면 …

스토리북 UI 테스트 자동화

---

src/components/BookDetailPage/ActionButtons.tsx
src/routes/RoutePath.ts
src/routes/index.tsx

- #88 
- 에딧 버튼 클릭시 포스팅 모달창 나오도록 기능 구현
- 종혁님이 만드신 공유 기능 구현 완료
- 종혁님께서 만드신 포스팅 모달창이 나오도록 구현하였습니다.
- 5분?
- 코드상 이상한 부분이 있다면 알려주세요!
https://github.com/user-attachments/assets/6be0fae0-2cc3-41b9-b5b9-40178c1e3c82

책 상세페이지에 포스팅 모달 공유 기능

---

.github/workflows/storybook-tests.yml

- #104
- CI 환경에서 Storybook 테스트 실패 문제를 해결하기 위해 workflow 파일을 수정하였습니다.
- CI 환경에서 사용되는 Node.js 버전을 22.x로 설정하는 matrix를 추가
- 실행 실패와 연관되는 부분은 아니지만 Node 버전을 현재 프로젝트 버전과 동일하게 명시해두는 게 좋을 것 같아서 추가하였습니다.
- storybook-coverage 작업에 Storybook 서버 실행 코드를 추가
- 스토리북 테스트에 앞서 Storybook 서버 실행이 필요한데 누락되어 있어서 추가하였습니다.
- Failed to load native binding 에러 발생으로 서버 실행이 안 되는 문제 npm update로 호환성 이슈 해결
- 예상 소요 시간 5분
- #98 에서 정상 동작하는 거 확인 완료하였습니다!

스토리북 ci 테스트 실행 실패 해결

---

src/components/Snackbar/SnackBar.tsx
src/features/Snackbar/snackbarSlice.ts

- #51 
- Snackbar 파일 내 import문 대소문자 수정
- snackbarSlice  파일 확장자를 .ts로 변경

snackbar 파일 대소문자 수정, 확장자 변경

---

src/components/Header/Header.tsx
src/pages/BookSearchPage/BookSearch.tsx

> #113 
헤더에서 검색 할 시 검색 결과가 바로 나오도록 작업
- 검색 결과가 없을 경우 검색 결과가 안나오고, 바로 검색페이지로 이동
- 검색 결가가 있을 경우 검색 결과 나오고 검색페이지로 이동
리뷰 소요 시간: 1~3분?
https://github.com/user-attachments/assets/7826560b-4308-4895-94f7-3dd8211d6a82

헤더 검색바 기능 구현

---

src/components/BookSearchPage/BestBookCard.tsx
src/components/BookSearchPage/BestBookCarousel.tsx
src/components/commons/Carousel.tsx
src/pages/BookDetailPage/BookDetailPage.tsx
src/pages/BookSearchPage/BookSearch.tsx

- #115 
- 검색페이지 반응형으로 디자인하였습니다.
- 디테일 페이지 약간의 디자인 변경 하였습니다.
> 모바일 반응형 고려하여 디자인하였습니다.
> 3분?
https://github.com/user-attachments/assets/7cad4dd8-af64-4152-85a1-b06f3f685ba6
https://github.com/user-attachments/assets/930d134c-e898-4389-9bf1-d9624c9c14ba

검색페이지 디자인/반응형 변경

---

src/components/BookDetailPage/ActionButtons.tsx
src/components/BookDetailPage/AddToLibraryDialog.tsx
src/components/BookDetailPage/BookDetailContent.tsx
src/components/BookDetailPage/BookDetailNavBar.tsx
src/components/BookDetailPage/BookDetailSection.tsx
src/components/BookDetailPage/BookInfoBox.tsx
src/components/BookDetailPage/BookIntroduceTab.tsx
src/components/BookDetailPage/FooterButtons.tsx
src/components/BookDetailPage/LeftBookDetailBox.tsx
src/components/BookDetailPage/RightBookDetailBox.tsx
src/components/BookSearchPage/BestSellerSection.tsx
src/components/BookSearchPage/BookSearchBar.tsx
src/components/BookSearchPage/SearchResult.tsx

- #143 
책검색, 책 상세페이지 관련 절대경로 수정을 하였습니다.
모두 절대경로로 바꾸었습니다.
리뷰 예상 시간 : 10~30초

책검색,책상세페이지 관련 컴포넌트들 절대경로 수정

---

src/features/BookSearchPage/api/bestBookGetApi.ts
src/features/BookSearchPage/api/bookDetailApi.ts
src/features/BookSearchPage/api/bookSearchApi.ts
vite.config.ts

- #138 
- #152
- 프록시 서버 다시 활성화했습니다!
- 로컬에서 정상 동작 확인하였습니다!

프록시 서버 다시 활성화하기

---

src/App.tsx
src/components/BookShelvesPage/BookDetailDialog/BookDetailDialog.tsx
src/components/LoginSignupPage/Login.tsx
src/components/LoginSignupPage/Login/Login.tsx
src/components/LoginSignupPage/Signup/Signup.tsx
src/components/MyPage/Feed/Feed.tsx
src/components/MyPage/Feed/PostFeedSection.tsx
src/components/MyPage/Feed/ReviewFeedSection.tsx
src/components/PostMorePage/PostMoreTemplate.tsx
src/components/PostingDetailPage/OtherPostingCard.tsx
src/components/PostingDetailPage/OtherPostingGrid.tsx
src/components/PostingDetailPage/PostingContent.tsx
src/components/PostingDetailPage/PostingHeader.tsx
src/components/PostingWritePage/PostingToolbar.tsx
src/components/PostingWritePage/PostingWrite.tsx
src/components/PostingWritePage/PostingWriteHeader.tsx
src/components/commons/BookSearchAutoComplete.tsx
src/components/commons/SnackBar.tsx
src/features/BookShelvesPage/slice/bookShelvesSlice.ts
src/features/BookShelvesPage/types/types.ts
src/features/MyPage/api/userFeedsApi.ts
src/features/PostingWritePage/types/types.ts
src/features/SignupPage/types.ts
src/features/user/types.ts
src/hooks/useTempSave.ts
src/pages/LikedPostMorePage/LikedPostMorePage.tsx
src/pages/LikedReviewMorePage/LikedReviewMorePage.tsx
src/pages/LoginSignupPage/LoginPage.tsx
src/shared/types/type.ts
src/utils/SignupPage/yupSchema.ts

- #151, #157 
- 타입 오류
- import 경로 오류
- 리뷰 예상 시간: 10분
- 오타나 타입이 맞지 않는 부분 오류만 일단 잡았습니다.
- 프로젝트 정상 작동 확인했으나, 제가 작성하지 않았던 코드의 경우에는 내부적으로도 작성하신 분의 의도에 맞게 작동하는지는 잘 모르겠습니다... 어차피 오류가 뜨던 부분이니 나중에 목업데이터이나 타입들 통일하면서 해결하면 될 것 같습니다.
- npm run build 실행하여 빌드 성공적으로 되는 것 확인하였습니다.
- 확인 부탁드립니다! @publdaze

배포 전 빌드 오류 해결

---

src/features/BookSearchPage/api/bestBookGetApi.ts
src/features/BookSearchPage/api/bookDetailApi.ts
src/features/BookSearchPage/api/bookSearchApi.ts
src/shared/config/aladinConfig.ts

- #155
- 운영 환경을 위해 프록시 서버 별도로 구축 후, 운영 환경에서는 해당 서버로 요청 보내도록 처리하였습니다.
- [노션](https://www.notion.so/goormkdx/AWS-28eb38b3ffd2498a88cef4c95ac4ddc2?pvs=4) 아직 정리는 못했지만, 미리 첨부해두겠습니다!
- AWS Lambda를 사용해서 서버리스로 프록시 서버 구축하고, API GateWay를 사용해 해당 프록시 서버에 접근할 수 있도록 처리해주었습니다.
<details>
<summary>프록시 서버 코드</summary>
<div markdown="1">
```js
import https from 'https';
export const handler = async (event) => {
const targetUrl = process.env.TARGET_URL || '';
const { path, headers, queryStringParameters } = event;
const queryString = queryStringParameters
? '?' +
Object.entries(queryStringParameters)
.map(([key, value]) => `${encodeURIComponent(key)}=${encodeURIComponent(value)}`)
.join('&')
: '';
const options = {
hostname: new URL(targetUrl).hostname,
path: path.replace('/aladinProxy', new …
```

 운영 환경에서 API gateway 프록시 서버로 연결되도록 처리

---

.github/workflows/build-and-deploy.yml

- #163
- main으로 코드 올라가면 자동 배포되도록 처리하였습니다!
- deploy 브랜치 기준으로 테스트 해본 결과 정상적으로 CI 수행되는 것 확인 완료하였습니다.
- 배포 코드가 실제로 동작하는 지 콘솔로도 찍어본 결과 확실히 정상 동작하는 거 확인 가능합니다!

배포 스크립트 작성

---

.github/workflows/build-and-deploy.yml

- Close #179
- supabase 환경 변수 추가된 거 깃헙 시크릿 키와 배포 스크립트에 추가하였습니다.
- 1분

 배포 스크립트 supabase 환경 변수 추가

---

src/components/PostingDetailPage/CommentSection.tsx
src/components/PostingDetailPage/PostingDetail.styles.ts
src/pages/PostingDetailPage/PostingDetailPage.tsx

- #201 
CommentSection 컴포넌트 구현
1. CommentSection 컴포넌트 구현
- useState를 사용한 댓글 목록 및 새 댓글 상태 관리
- 댓글 목록 렌더링 기능
- 새 댓글 입력 및 제출 기능 구현
- ui 확인을 위한 기본적 기능만 구현한 상태
2. PostingDetailPage 컴포넌트 수정
- 포스팅 카드와 댓글 섹션을 별도의 Box 컴포넌트로 분리
리뷰 예상 시간: 20분 내외
집중 리뷰 부분: ui에서 수정할 부분 있으면 알려주세요!
https://github.com/user-attachments/assets/14fbb220-db19-48ed-9ea4-587bf125da23

포스팅 댓글 기능 구현

---

src/components/PostingDetailPage/PostingContent.tsx

- #205 
- 포스팅 상세 페이지 영어 내용 줄바꿈 관련 이슈 해결
- 너비 설정 및 줄바꿈 관련 css 추가
```
wordWrap: 'break-word',
overflowWrap: 'anywhere',
width: '100%',
```
- 리뷰 예상 시간: 1분
- 줄바꿈 정상 작동 확인

포스팅 상세 페이지 영어 내용 줄바꿈 이슈

---

.github/workflows/build-and-deploy.yml

- #254
- 추가된 환경 변수 배포 스크립트에 업데이트 해주었습니다.
- #182에서 추가된 환경 변수에 대한 배포 스크립트 추가
- 1분

배포 스크립트 수정

---

.depcheckrc
.storybook/main.ts
tsconfig.app.json

- close #255
- msw 잔류 코드 삭제 하였습니다.
- 1분

msw 잔류 코드 삭제

---

src/hooks/usePerformAutoLogin.ts
src/hooks/useSetAutoLogin.ts

- #260 
- userSlice loginSuccess parameter 오류 해결
- username 파라미터 추가
- 리뷰 예상 시간: 1분

userSlice loginSuccess parameter 오류

---

src/components/AdditionalInfo/AdditionalInfo.tsx
src/components/BookDetailPage/ActionButtons.tsx
src/components/BookDetailPage/BookFeedTab.tsx
src/components/BookDetailPage/BookMyReview.tsx
src/components/BookSearchPage/BestBookCard.tsx
src/components/BookSearchPage/SearchBookCard.tsx
src/components/BookShelvesPage/BookDetailDialog/BookDetailDialog.tsx
src/components/FeedPage/PostCard/PostCardFooter.tsx
src/components/FeedPage/PostTypeSelectDialog/PostTypeButton.tsx
src/components/Header/Header.tsx
src/components/Header/userMenu.tsx
src/components/LoginSignupPage/Login/Login.tsx
src/components/LoginSignupPage/Signup/Signup.tsx
src/components/MyPage/Feed/OneLineReviewSection.tsx
src/components/MyPage/Feed/PostingSection.tsx
src/components/MyPage/FollowList.tsx
src/components/MyPage/Library/BookshelfCard.tsx
src/components/NotFoundPage/NotFoundContent.tsx
src/components/PostingDetailPage/PostingHeader.tsx
src/components/PostingWritePage/PostingWriteHeader.tsx
src/components/ReviewMorePage/ReviewMorePageTemplate.tsx
src/features/SNSLogin/auth/KakaoCallback.tsx
src/pages/MyPage/MyPage.tsx
src/pages/PasswordChkPage/PasswordChkPage.tsx
src/routes/RoutePath.ts
src/routes/index.tsx
src/shared/utils/navigation.ts
tsconfig.app.json

- #262 
- naviagator & routes 리팩토링
- 다른 페이지로 이동하는 함수 navigation에 정의
- navigation에 정의된 함수 이용
- 경로 RoutePath.ts 이용
- 리뷰 예상 시간: 5분
- 경로 RoutePath이용하고 함수만 새로 정의해서 바꿔놓기만 한 작업이라 너무 꼼꼼히 보실 필요는 없을 것 같습니다!

naviagator & routes 리팩토링

---

src/components/commons/NonTitleDialog.tsx

- #278
- NonTitleDialog 오류 해결
- lazy 로 동기식 입력에 응답하는 동안 컴포넌트 중단
- suspense 처리
- 리뷰 예상 시간: 1분

NonTitleDialog 오류 해결
