tsconfig.app.json

- #40
- src 기준이 아닌 지정한 절대 경로로 자동 완성되도록 수정해주었습니다.
- 예상 소요 시간 1분

절대 경로 자동 완성 src 기준으로 되는 문제 해결

---

src/components/commons/HybridDialog.tsx

- #52 
- `onClose={handleClose}` 추가하여 다이얼로그 외부 클릭 시에도 닫히도록 처리하였습니다.
- e.stopPropagation(); 이전에 이벤트 전파 문제가 발생하는 것 같아서 해당 코드 작성해두었는데, 다이얼로그 활용하는 부분에서 문제가 있었던 것이여서, 불필요한 코드라 지금은 삭제해주었습니다.
<details>
<summary>참고 - 이벤트 전파 문제 발생하는 경우</summary>
<div markdown="1">
https://github.com/user-attachments/assets/f819d2d4-e4cc-4b82-82af-988ab7a1c008
```tsx
<Button
onClick={() => {
setOpen(true);
}}
>
<Typography>{count}</Typography>
<Typography>{label}</Typography>
<HybridDialog
open={open}
setOpen={setOpen}
title={label}
contentNode={<FollowList />}
/>
</Button>
```
react portal을 사용하여 DOM 위치 상으로는 React 트리와 분리되어 위치하지만, 이벤트 전파는 React 트리를 따라서 동작하기 때문에, 클리 요소 하위에 다이얼로그를 배치하게 되면, 이벤트 전파가 일어나면서 다이얼로그 클릭 시 버튼 클릭 이벤트가 발생하게 됩니다.
```tsx
<>
<Button
onClick={() => {
setOpen(true);
}}
> …
```

다이얼로그 외부 클릭 시 안 닫히는 문제 해결

---

src/App.tsx
src/components/MyPage/FollowList.tsx
src/components/MyPage/TabSection.tsx
src/components/MyPage/UserInfoSection.tsx
src/components/MyPage/UserInfoSummary.tsx
src/pages/MyPage/MyPage.tsx

- #37
- 팔로워 팔로잉 기능 구현하였습니다.
- 팔로워, 팔로잉 버튼 클릭 시 다이얼로그에 해당 리스트들 뜨도록 처리하였습니다.
- 각 리스트에서도 아바타와 이름의 경우 클릭 이벤트를 넣어주어, 클릭 시 해당 사용자의 페이지로 이동할 수 있도록 처리하였습니다.
- userId에 따른 페이지 라우팅 되도록 처리하였습니다.
- 이동된 페이지에 대한 유저 정보 처리는 API 연동 후 정상적으로 반영될 예정입니다. (현재는 이동만 하고, 동일한 목데이터를 사용합니다.)
- 삭제 버튼 클릭 시에 대한 처리는 핸들러만 먼저 생성해둔 상태이고, 이후 API 만들어지면 연동이 필요합니다.
- 리뷰 예상 시간 10분

팔로워 팔로잉 다이얼로그 구현

---

src/components/FeedPage/OneLineReviewDialog.tsx
src/components/FeedPage/PostingDialog.tsx
src/components/FeedPage/WriteDialog.tsx
src/components/commons/BookSearchAutoComplete.tsx
src/components/commons/HybridDialog.tsx
src/components/commons/TextEditor.tsx
src/pages/MainPage/Main.tsx
src/shared/types/type.ts

- #47 #59 #34
- 포스트 작성 기능 구현
- 포스트 타입 선택 다이얼로그 구현 (Hybrid Dialog 사용)
- 한줄평 작성 다이얼로그 구현
- 별점 기능 추가 필요 (#56)
- 포스팅 작성 다이얼로그 구현
- 포스팅 작성 후 포스팅 상세 페이지로 이동 (#55)
- 공통 컴포넌트
- BookSearchAutoComplete 추가
- 책 검색 위한 AutoComplete 검색창 구현
- HybridDialog 변경
- 뒤로가기 버튼 추가
- 제목 상단 가운데 위치
- 액션 버튼 전체 너비 차지하도록 하단 위치
- 리뷰 예상 시간: 10분
- 공통 컴포넌트 사용할 수도 있으니 그 부분 봐두시면 좋을 듯합니다.
- 포스트 타입 선택 다이얼로그
- 한줄평 작성 다이얼로그
- 포스팅 작성 다이얼로그
- 책 검색 AutoComplete

포스트 작성 기능 구현

---

src/components/FeedPage/WriteDialog.tsx
src/components/commons/HybridDialog.tsx
src/components/commons/NonTitleDialog.tsx

- Close #89
- 제목 없는 공통 다이얼로그 구현하고 패딩 없애기 진행하였습니다.
- 제목 없는 다이얼로그 사용하고 싶으면 이제 `NonTitleDialog` 컴포넌트 사용하시면 됩니다! (추후 스토리북도 작성하면 어떤 다이얼로그가 있고 props에 따라 어떻게 활용 가능한 지 파악하기 용이할겁니다! 조금만 기다려주세용!)
- 액션 부분 패딩은 버튼이 전체 너비 차지하도록 디자인 되어있는 것 같아서, 이부분은 패딩 0 남겨두었습니다!
- @deenuit113 `WriteDialog`에도 반영해두었습니다! 또 사용되는 부분 있다면 참고해서 반영해주시면 될 것 같습니다.
- 일단 닫기 버튼 action으로 처리하긴 했는데, 타입 관련해서 처리할 때, 경우에 따른 필수값 처리하는 게 직관적이지 않은 경우가 있더라구요. 일단 title 항상 옵셔널하게 처리되어 있는데, 추후 배포까지 끝나고 시간이 남는다면 다시 설계 다듬고 리팩토링 작업 맡아서 해볼까 싶습니다!

제목 없는 공통 다이얼로그 구현

---

src/App.tsx
src/components/Header/Header.tsx
src/components/LoginSignupPage/Login.tsx
src/features/SNSLogin/auth/KakaoCallback.tsx
src/features/user/userSlice.ts
src/store/index.tsx

- #23 
- #71 
- #79 
- 카카오 로그인 시 헤더가 동적으로 업데이트되지 않는 문제 수정
➕userSlice 파일을 이동, 스토어 파일 통합
- 카카오 로그인 버튼 클릭 시 카카오 인증 URL로 리디렉션하는 로직 추가
- 사용자 정보를 로컬 스토리지에서 가져와 로그인 처리 후 Redux 상태를 업데이트하도록 수정
- 카카오 API로부터 받은 액세스 토큰을 사용하여 사용자 정보를 가져와 Redux 스토어에 저장
-> 로그인 상태에 따라 헤더의 로그인 버튼과 프로필 메뉴가 올바르게 렌더링되는것을 확인함
- store/userSlice 파일을 src/features/user 디렉토리로 이동하여 프로젝트 구조 개선
- store/store.tsx 파일을 store/index.tsx에 통합하여 스토어 관리 구조 간소화
리뷰 예상 시간: 10분 미만
집중 리뷰 부분: 카카오 로그인 처리 및 Redux 상태 업데이트 로직, 파일 이동에 따른 import 경로 변경 사항, 스토어 통합 및 경로 수정 사항 검토
https://github.com/user-attachments/assets/f853d552-5f1f-4813-b2a7-fca9f544c5a1

카카오 로그인 헤더 버튼 동작 이슈

---

src/components/Header/Header.tsx
src/components/LoginSignupPage/Signup.tsx
src/features/user/types.ts
src/features/user/userApi.ts
src/features/user/userSlice.ts
src/mocks/handlers/user.ts
src/pages/EditAccountPage.tsx/EditAccountPage.tsx
src/pages/PasswordChkPage/PasswordChkPage.tsx
src/routes/RoutePath.ts
src/routes/index.tsx
src/store/index.tsx
src/store/userSlice/userSlice.tsx

- #93
- 사용자 정보 수정 페이지 구현하였습니다.
[비밀번호확인 페이지]
- 개인 정보 수정으로 들어갔을 때, 비밀번호 확인이 수행되지 않은 경우에는 비밀번호 확인을 먼저 진행할 수 있도록 비밀번호 확인 페이지로 리다이렉트 됩니다.
- 목업 api로 비밀번호 확인하도록 구현하였습니다. (이때, 목업 비밀번호는 `P@ssw0rd1!`로 이와 동일할 경우 통과되도록 하였습니다.)
- 비밀번호가 틀릴 경우에는 스낵바를 통해 에러 메시지를 적용합니다.
- 비밀번호 확인이 성공적으로 수행되면 개인 정보 수정 페이지로 돌아갑니다.
[개인정보수정 페이지]
- 사용자 이름, 휴대폰 번호, 비밀번호를 개별적으로 수정할 수 있는 기능을 추가하였습니다. (목업 api 연동)
- 사용자 아바타 이미지를 업로드 및 삭제할 수 있는 기능 추가. (이때, 이미지를 실제 서버에 올리고 url을 받아올 수는 없어서 목업으로 한 url에 대한 처리만 가능합니다.)
- 각 요청 성공 및 실패 시 Snackbar를 활용하여 사용자에게 알림 표시되도록 하였습니다.
- 30분..?
- 개인정보수정 form에 대한 유효성 검사 이 PR 머지 후 별도 PR으로 올리겠습니다.
https://github.com/user-attachments/assets/a511d64a-c682-44b5-8772-5636c25f10a4

사용자 정보 수정 페이지 구현

---

src/components/MyPage/Feed/Feed.tsx
src/components/MyPage/Feed/LikedFeedTabPanel.tsx
src/components/MyPage/Feed/PostFeedSection.tsx
src/components/MyPage/Feed/ReviewFeedSection.tsx
src/components/MyPage/Feed/UserFeedTabPanel.tsx
src/components/PostMorePage/PostMoreTemplate.tsx
src/components/ReviewMorePage/ReviewMorePageTemplate.tsx
src/features/MyPage/api/userFeedsApi.ts
src/mocks/handlers/user.ts
src/pages/LikedPostMorePage/LikedPostMorePage.tsx
src/pages/LikedReviewMorePage/LikedReviewMorePage.tsx
src/pages/PostMorePage/PostMorePage.tsx
src/pages/ReviewMorePage/ReviewMorePage.tsx
src/routes/index.tsx

- #117
- 피드 탭 더보기 페이지
- 책 상세 페이지에서 사용되는 더보기 페이지 UI 분리해주고, 피드 탭 더보기 페이지 새로 생성하여 구현하였습니다.
- 15분?
- 머리가 안 돌아가서, 놓친 부분이 좀 있을 수도 있을 것 같은데, 일단 PR 더 늦어지면 안 될 것 같아서 먼저 올리고, 추후 다시 검토해보고 새 이슈 파서 부족한 부분 보완하겠습니다.
https://github.com/user-attachments/assets/93472ad8-cfde-408e-bf8d-8c80ca9a32bf

피드 탭 더보기 페이지 구현

---

src/features/BookSearchPage/api/bestBookGetApi.ts
src/features/BookSearchPage/api/bookDetailApi.ts
src/features/BookSearchPage/api/bookSearchApi.ts
src/main.tsx
vite.config.ts

- Close #138
- 운영서버에서 알라딘 api 호출 문제, msw로 인한 api 호출 문제 해결하였습니다.
- [프록시 서버 설정](https://vite.dev/config/server-options.html#server-proxy)이 개발 서버 대상이라서 운영 서버에서 동작 안 되는 문제를 해결하였습니다.
- s3에서 프록시 서버 구축하려면 별도의 프록시 서버 구축이 필요해보여서 프록시 서버없이 redux toolkit baseurl 설정을 통해 알라딘 api 호출 경로 직접 지정해주었습니다.
- msw 목업 서버 저희는 운영서버에서도 사용하는데, 개발서버에서만 동작되도록 구현되어 있어서 해당 부분 주석 처리해두었습니다.
- 혹시나 나중에 supabase로나 api 구현하게 될 가능성도 고려하여, 삭제 안 하고 일단 주석으로만 처리해두었습니다.
- 5분

운영서버 api 동작 안 하는 문제 해결

---

src/components/PostingWritePage/PostingWrite.styles.ts
src/components/PostingWritePage/PostingWrite.tsx
src/hooks/useTempSave.ts

- #164
- 책 상세페이지에서 포스팅 작성시, 임시저장 로드 다이얼로그가 표시되는 이슈 해결
- location state 로 책 받아올 시(책 상세페이지에서 글 작성), 임시저장 및 로드가 되지 않도록 로직 수정
- 리뷰 예상 시간: 1분

포스팅 작성 임시저장 로드 다이얼로그 표시 이슈 해결

---

src/pages/LikedPostMorePage/LikedPostMorePage.tsx
src/pages/LikedReviewMorePage/LikedReviewMorePage.tsx

- #170 
- 게시물 더보기 페이지 무한스크롤 로직 변경
- 게시물 불러올 때 현재 게시물의 개수가 전체 게시물의 개수보다 적을 때 데이터를 불러오도록 함
```
setHasMore(reviews.length + newReviews.length < data.totalFeeds);
```
- 리뷰 예상시간: 1분

게시물 더보기 무한스크롤 이슈 해결

---

src/components/AdditionalInfo/AdditionalInfo.styles.ts
src/components/AdditionalInfo/AdditionalInfo.tsx
src/components/AdditionalInfo/AdditionalInfo.types.ts
src/pages/AdditionalInfoPage/AdditionalInfoPage.tsx
src/routes/RoutePath.ts
src/routes/index.tsx

- #188 
AdditionalInfo 컴포넌트 구현 및 라우팅 설정 업데이트
1. AdditionalInfo 컴포넌트 구현
- 아이디, 성별, 나이 입력 폼 구현
- Yup을 사용한 폼 유효성 검사
- 아이디 중복 확인 기능 간단 구현
2. 라우팅 설정 업데이트
리뷰 예상 시간: 20분?
집중 리뷰 부분: 
제 기억상 회의 때 아이디, 성별, 나이 부분이 필요했다고 생각나서 일단은 세개만 넣었습니다. 더 필요한게 있다면 알려주세요.
제가 목요일에 프로젝트 작업 진행이 불가능할 것 같아서 일단은 최대한 간단하게만 구현했습니다.
https://github.com/user-attachments/assets/816a3dc5-8c08-4b49-ba3c-24bf8b8cf55d

카카오 회원가입 후 정보 입력 페이지 구현

---

index.html
src/components/Header/userMenu.tsx
src/pages/EditAccountPage.tsx/EditAccountPage.tsx
src/pages/PasswordChkPage/PasswordChkPage.tsx
src/routes/RoutePath.ts

- #186 
SEO 메타 태그 추가 및 EDIT_ACCOUNT 라우트 경로 변경
1. SEO 최적화:
- description 메타 태그 추가
- canonical 링크 추가
- Open Graph 메타 태그 최적화
2. 라우트 경로 변경:
- EDIT_ACCOUNT 경로를 '/edit-account'에서 '/profile/edit'로 변경
->posting_write, posting_edit처럼 계층 구조 사용
- 관련 컴포넌트 및 네비게이션 로직 업데이트
리뷰 예상 시간 : 10분 미만
집중 리뷰 부분 : HTML 구조 변경 및 메타 태그 추가 부분
➕경로 수정할게 딱히 있진 않아서 일단은 개인정보수정페이지만 수정하였는데 시중에 사이트를 찾아보니 my-page보단 myProfile 이런식으로 사용하던데 이대로 my-page해도 괜찮은지 아니면 수정할지 알려주세요
➕저희가 로고가 있지 않아서 메타 태그에 이미지가 없는 상태여서 로고나 아이콘 있으면 좋을 것 같아요

SEO 메타 태그 추가 및 라우트 경로 변경

---

src/components/AdditionalInfo/AdditionalInfo.tsx
src/components/LoginSignupPage/Login/Login.tsx
src/components/LoginSignupPage/Signup/Signup.tsx
src/features/SNSLogin/auth/KakaoCallback.tsx
src/features/user/additionalInfoApi.ts
src/features/user/userApi.ts
src/features/user/userSlice.ts
src/hooks/useAuthStateChange.ts
src/hooks/usePerformAutoLogin.ts
src/hooks/useSetAutoLogin.ts
src/pages/EditAccountPage.tsx/EditAccountPage.tsx
src/pages/PasswordChkPage/PasswordChkPage.tsx
src/routes/index.tsx
src/shared/types/type.ts
src/store/index.tsx
src/utils/SignupPage/yupSchema.ts
src/utils/deleteUserFiles.ts

- #196 #198 #202
- sns 로그인 시 추가 정보 입력 페이지로 이동
- 정보 수정 페이지 구현
- 추가 정보 입력 페이지
- 추가 정보 입력 API 구현
- 정보 수정 페이지
- 이메일 / SNS 로그인 시 조건부로 비밀번호 확인 페이지로 이동
- SNS 로그인 시 첫 로그인에만 카카오톡 프로필 사진 적용
- 유저 정보 수정 API 구현
- 회원 탈퇴 기능 구현
- 10분

추가 정보 입력 페이지 & 정보 수정 페이지

---

src/components/PostMorePage/PostMoreTemplate.tsx
src/components/ReviewMorePage/ReviewMorePageTemplate.tsx

- #197 
리뷰 및 포스트 목록에서 삭제 기능 구현
- ReviewMorePageTemplate과 PostMoreTemplate에 삭제 기능 추가
- 삭제 모드 토글 버튼 구현
- 체크박스를 통한 아이템 선택
- 선택된 아이템 삭제 기능 구현 (임시 로직)
예상 리뷰 시간: 20분
집중 리뷰 부분 : 
1. ReviewMorePageTemplate과 PostMoreTemplate에 삭제버튼을 추가했습니다. 지금은 상세페이지->더보기페이지랑 마이페이지 더보기 페이지 모두 삭제버튼이 뜹니다.
2. 임시 로직 구현한 상태라 다른 수정사항이 보인다면 알려주세요!
1. 한줄평 더보기 페이지
https://github.com/user-attachments/assets/532d4e9a-a193-4ebe-aa91-98e8d5064f54
2. 포스팅 더보기 페이지
https://github.com/user-attachments/assets/4513ef02-8a2a-402b-ac70-75076ca8f420

더보기 페이지 삭제 관련 UI 구성

---

.github/workflows/storybook-tests.yml

- Close #210
- 캐싱이 꼬여 스토리북 서버 실행 환경이 정상적으로 되지 않는 문제를 해결하였습니다.
- <img width="400" alt="image" src="https://github.com/user-attachments/assets/61ff8b8b-458a-4966-9df8-fdeadfb4d3f5" />
위 문제 해결하였습니다.
- 기존 캐싱이 nodemodule 관련 캐싱과, playwright(스토리북 서버) 관련 캐싱이 동시에 이루어졌는데, CI 환경에서 불완전한 복원이 발생할 가능성이 있어서 nodemodule만 캐싱하고, playwright(스토리북 서버) 캐싱은 필요한 곳에서 매번 설치 및 실행해주는 방식으로 변경하였습니다.
- npm update로 인한 패키지 버전 갱신으로 워크플로우 내 작업 간에 설치된 패키지 버전이 달라지지 않고 일관성을 유지할 수 있도록 처리해주었습니다.
- 2분
- <img width="369" alt="image" src="https://github.com/user-attachments/assets/a4936ec7-1313-483d-844d-96e8ecf95b75" /> 해당 문제는 #213 에서 해결하였습니다! 현재 PR에서는 실패 발생하는 게 정상입니다!

깃헙 액션 스토리북 서버 실행 캐싱 문제로 인한 실패 해결

---

.github/workflows/storybook-tests.yml

- Close #209
- 기존에 사용하였던 artifact v3가 deprecated 되어 v4로 마이그레이션 해주었습니다.
- <img width="962" alt="image" src="https://github.com/user-attachments/assets/034dc0cc-8027-4d8d-9c2c-c9379731c06c" />
위 문제 해결 완료하였습니다.
- [참고 자료](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/)
- 1분
- artifact 버전 외 playwright 서버 관련한 문제 발생하는데 별도 PR에서 해결 예정입니다! (현재 2군데에서 실패하는 건 playwright 서버 관련!) #214

Deprecated된 artifact actions로 인한 버그 픽스

---

src/components/MyPage/FollowList.tsx

- #225
- 팔로우 버튼 표시 로직 변경
```
{currentUserId !== userId && (
<Button
variant="contained"
size="small"
onClick={() => handleToggleFollow(userId)}
>
{isFollowing ? '언팔로우' : '팔로우'}
</Button>
)}
```
```currentUserId (접속중인 유저의 id)```와 ```userId (현재 위치한 유저 페이지의 userId)``` 가 다를 때 표시가 아니라 팔로우 리스트의 각각의 유저 id가 다를 때 표시해야 함.
> ```userId => id``` 로 변경
- 1분

팔로우 리스트에 팔로우 버튼 미표시 버그 해결

---

src/components/MyPage/FollowButton.tsx
src/components/MyPage/UserInfoSection.tsx
src/pages/MyPage/MyPage.tsx

- #222 
- 다른 사용자의 마이페이지에 팔로우/언팔로우 버튼을 구현
- FollowButton컴포넌트를 생성하여 사용자의 팔로우 상태를 확인하고 토글하는 기능 제공
- followApi를 사용하여 팔로우 상태를 확인하고 버튼을 클릭하면 팔로우 상태 변경
리뷰 예상 시간: 5분
집중 리뷰 부분: 팔로우 상태 확인 및 토글 로직

다른 사용자의 마이페이지에 팔로우/언팔로우 버튼 구현

---

src/components/PostingWritePage/BookSearchPopover.tsx
src/components/PostingWritePage/PostingWrite.tsx

- #239 
- BookSearchPopover.tsx 파일에서 BookSearchAutoComplete 로 props 넘길 때
searchQuery, setSearchQuery 값을 props주는데 BookSearchAutoComplete는 이 2개의 props를 받지 않아서 오류 발생하였음.
- searchQuery 값을 가장 자식컴포넌트가 useState로 상태 관리 되고 있는 거 같아서 전 부모컴포넌트들에게 props로 받고 있어서 그 값들을 모두 삭제 하였습니다.
- @deenuit113 혹시 이렇게 고쳐도 맞는건지 확인해주시면 감사하겠습니다.
- 이부분이 포스팅작성페이지에 책 검색하는 부분이 맞는지? 궁금합니다. 고치고나서 검색 작동 잘 되는지 확인 하였습니다.

Props 관련 오류 수정

---

package-lock.json
package.json
src/components/FeedPage/PostCard/PostCard.styles.ts
src/components/FeedPage/PostCard/PostCard.tsx
src/components/FeedPage/PostCard/PostCardSkeleton.tsx
src/hooks/useColumnCount.ts
src/pages/MainPage/Main.tsx

- Close #242
- 피드 페이지 CLS 수치 `1.011`(최신 develop 브랜치 커밋 ba765892a67d9268e9c761cd5e394851ba47ff89 기준) -> `0.001`으로 개선하였습니다.
- MUI Masonry 대신 **flex와 js로 동적 column을 사용하는 방식**으로 변경하였습니다.
- 기존에 사용하던 MUI Masonry 컴포넌트의 경우, 1개의 column으로 렌더링 후 설정한 column 수로 펼쳐지는 형태로 성능이 저하되는 문제가 있어 이를 대체하며 성능을 개선하였습니다.
- PostCard에 **스켈레톤을 적용**하여 비동기 데이터로 새로 추가되는 영역에 대해 미리 공간 확보하여 성능을 개선하였습니다.
- PostCard를 포스트, 한줄평 각각의 **크기를 고정**하여, 스켈레톤과 크기를 맞춰주며 layout shift를 방지하였습니다.
- 기존 PostCard는 content 길이에 따라 유동적으로 변하는 스타일이었지만, 성능상 이점을 좀 더 취하기 위해 고정 크기로 변경하였습니다.
위의 사항들을 적용 후 위험 수치였던 `1.011`에서 안전 수치인 `0.001`으로 개선되었습니다.
(측정 시마다 수치에 조금씩 변동은 있지만, 위험 수치냐, 안전 수치냐의 여부에 있어서는 항상 동일하게 측정되었습니다.)
+)
- Masonry 컴포넌트 사용하지 않음에 따라, mui lab 라이브러리도 삭제하였습니다.
- 스켈레톤 반응형에 따라서도 확인 후 처리하였습니다.
예상 리뷰 시간 10분 …

피드 페이지 cls 개선

---

src/components/MyPage/Feed/OneLineReviewSection.tsx
src/components/MyPage/Feed/PostingSection.tsx
src/components/MyPage/Library/BookshelfCard.tsx

- #232 
- 내 피드와 좋아요한 피드에서 한줄평 및 포스팅이 없을 때 표시할 메시지 추가
- 빈 책장 카드의 크기를 조정
- 빈 책장에 "책이 없습니다" 메시지 추가
- **내 피드**: "작성한 한줄평이 없습니다"와 "작성한 포스팅이 없습니다" 메시지 추가
- **좋아요한 피드**: "한줄평에 좋아요를 누른 항목이 없습니다"와 "포스팅에 좋아요를 누른 항목이 없습니다." 메시지 추가
- 빈 책장 카드의 너비를 고정하여 책이 있는 경우와 없는 경우의 크기를 일관되게 유지하도록 수정
- 책이 없는 경우 "책이 없습니다"라는 메시지를 가운데 정렬하여 표시하도록 구현
리뷰 예상 시간: 10분
집중 리뷰 부분: Grid 컴포넌트 사용 -> Grid2 사용시 타입스크립트 오류 발생해서 Gird로 변경했습니다
메시지의 문구와 레이아웃 확인

마이페이지 UI 수정

---

src/components/PostingDetailPage/PostingDetail.styles.ts
src/pages/PostingDetailPage/PostingDetailPage.tsx

포스팅 상세페이지 컨테이너 CSS 우선순위 변경
스타일 파일 > 컴포넌트
Resolves: #249
- #249 
- 포스팅 상세페이지 레이아웃 관련 CSS 코드 위치 옮김
- 컨테이너 컴포넌트의 레이아웃 관련 CSS가 스타일 파일에 작성되었을 때는 우선순위가 낮아 MUI 기본 CSS와 충돌하는 것 같음. 
- 컴포넌트에 직접 작성
- 추후 MUI CSS Reset 필요
- 참고자료: - [MUI 공식문서](https://mui.com/material-ui/react-css-baseline/?srsltid=AfmBOoo1sjzLtvghBwEpx5i-3PyYezb7VCxSiato-eXpdgXscCarAYdd)
- 리뷰 예상 시간: 1분

포스팅 상세 페이지 레이아웃 깨짐 현상 해결

---

src/components/FeedPage/PostCard/PostCardFooter.tsx

- #251 
- 피드페이지에서 로그아웃 시 좋아요 상태 리페치
- 비로그인 상태에서 좋아요 처리
- 로그아웃 시 좋아요 상태 조회 쿼리 강제 리페치
- 비로그인 상태에서 좋아요 버튼 누를 시, 스낵바 표시 후 로그인 페이지로 이동
- 리뷰 예상 시간: 3분
- 버튼 비활성화 처리도 해보았지만 좋아요 수가 눈에 띄지 않고 로그인 & 회원가입 유도하는 게 나을 것 같아서 로그인 페이지로 이동하도록 했습니다.

피드페이지 좋아요 버튼 로직 수정

---

src/components/BookDetailPage/BookFeedTab.tsx
src/components/BookDetailPage/BookMyReview.tsx
src/features/BookDetailPage/api/bookOwnReviewApi.ts

- #248 
- 로그인 하지 않은 상태에서 책 상세페이지에 리뷰탭이 오류나는 현상 수정
- 한줄평, 포스팅 수는 현재 undefined를 반환해서 ( 만약 리뷰, 한줄평이 없을때 ) 값이 없다면 0을 반환하도록 함
-  리뷰가 없습니다, 포스팅이 없습니다가 보이지 않는 부분은 
- 조건문을 수정하여 배열이고, 요소가 있을 때만 포스트, 한줄평을 렌더링 하도록 수정
- @deenuit113  api 오류 처리가 따로 필요할 것 같습니다!

책 상세페이지 리뷰 탭 오류 수정

---

package-lock.json
package.json
src/features/user/userApi.ts

- #267 
- 프로필 사진 업로드 시 이미지 압축
- 이미지 최대 너비 & 높이 최대 500px로 고정
- 이미지 최대 용량 1MB > 네트워크 대역폭 절약
- web worker 사용 (메인 스레드와 분리하여 백그라운드에서 이미지 압축 > UI랑 별개로 작동)
- browser-image-compression
- 리뷰 예상시간: 1분
- 이미지 크기 1MB이하로 줄임
- supabase storage 캡처

프로필 사진 업로드 시 이미지 압축
